--liquibase formatted sql
--changeset tomknapp:20250203-2-create-telephone.sql
CREATE TABLE staging.telephone (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NULL,
    telephone_number text NOT NULL,
    std_telephone_number text NOT NULL,
    is_verified boolean NOT NULL DEFAULT false,
    date_created timestamp
    with
        time zone NOT NULL DEFAULT now (),
        date_modified timestamp
    with
        time zone NOT NULL DEFAULT now ()
);

ALTER TABLE staging.telephone ADD CONSTRAINT telephone_pkey PRIMARY KEY (id);

ALTER TABLE staging.telephone ADD CONSTRAINT fk_telephone_customer FOREIGN KEY (customer_id) REFERENCES staging.customer (id) ON DELETE CASCADE;

--rollback DROP TABLE staging.telephone;
