--liquibase formatted sql
--changeset tomknapp:20250203-3-create-email.sql
CREATE TABLE staging.email (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NULL,
    email_address text NOT NULL,
    std_email_address text NOT NULL,
    is_verified boolean NOT NULL DEFAULT false,
    date_created timestamp
    with
        time zone NOT NULL DEFAULT now (),
        date_modified timestamp
    with
        time zone NOT NULL DEFAULT now ()
);

ALTER TABLE staging.email ADD CONSTRAINT email_pkey PRIMARY KEY (id);

ALTER TABLE staging.email ADD CONSTRAINT fk_email_customer FOREIGN KEY (customer_id) REFERENCES staging.customer (id) ON DELETE CASCADE;

--rollback DROP TABLE staging.email;
