--liquibase formatted sql
--changeset tomknapp:20250205-1-create-audit.sql
CREATE TABLE public.audit (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    audit_type text NOT NULL,
    audit_date timestamp
    with
        time zone NOT NULL DEFAULT now ()
);

ALTER TABLE public.audit ADD CONSTRAINT audit_pkey PRIMARY KEY (id);

--rollback DROP TABLE public.audit;
