--liquibase formatted sql
--changeset tomknapp:20250203-4-create-address.sql
CREATE TABLE staging.address (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id integer NULL,
    address_line_1 text NULL,
    address_line_2 text NULL,
    address_line_3 text NULL,
    address_line_4 text NULL,
    address_line_5 text NULL,
    postcode text NULL,
    std_address_line_1 text NULL,
    std_address_line_2 text NULL,
    std_address_line_3 text NULL,
    std_address_line_4 text NULL,
    std_address_line_5 text NULL,
    std_postcode text NULL,
    date_created timestamp
    with
        time zone NOT NULL DEFAULT now (),
        date_modified timestamp
    with
        time zone NOT NULL DEFAULT now ()
);

ALTER TABLE staging.address ADD CONSTRAINT address_pkey PRIMARY KEY (id);

ALTER TABLE staging.address ADD CONSTRAINT fk_address_user FOREIGN KEY (customer_id) REFERENCES staging.customer (id) ON DELETE CASCADE;

--rollback DROP TABLE staging.address;
