version: 2

# Define the raw data sources that can be used within dbt
sources:
  - name: postgres_example_db
    description: "A sample database created by liquibase migrations"
    database: postgres
    schema: public
    tables:
      - name: customer
        description: "Customers within the system"
      - name: address
        description: "Addresses relating to customers"

models:
  - name: customers
    description: Flattened view of customers
    columns:
      - name: id
        tests:
          - unique
          - not_null

  - name: customer_geography
    description: Flattened view of the customers most recent location
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
